spring:
  application:
    name: ${SPRING_APPLICATION_NAME:gira-backend}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/gira}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:5}
      maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:20}
      idle-timeout: ${SPRING_DATASOURCE_IDLE_TIMEOUT:300000}
      connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:20000}
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_FORMAT_SQL:false}
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}
    database: ${SPRING_REDIS_DATABASE:0}
    timeout: ${SPRING_REDIS_TIMEOUT:60000}
    lettuce:
      pool:
        max-active: ${SPRING_REDIS_POOL_MAX_ACTIVE:8}
        max-idle: ${SPRING_REDIS_POOL_MAX_IDLE:8}
        min-idle: ${SPRING_REDIS_POOL_MIN_IDLE:0}
        max-wait: ${SPRING_REDIS_POOL_MAX_WAIT:-1ms}
  cache:
    type: ${SPRING_CACHE_TYPE:redis}
    redis:
      time-to-live: ${SPRING_CACHE_REDIS_TIME_TO_LIVE:3600000}
      cache-null-values: ${SPRING_CACHE_REDIS_CACHE_NULL_VALUES:false}
  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:10MB}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:10MB}

server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: ${SERVER_COMPRESSION_ENABLED:true}
    mime-types: ${SERVER_COMPRESSION_MIME_TYPES:application/json,application/xml,text/html,text/xml,text/plain}
    min-response-size: ${SERVER_COMPRESSION_MIN_RESPONSE_SIZE:1024}

springdoc:
  swagger-ui:
    path: ${SPRINGDOC_SWAGGER_UI_PATH:/swagger-ui.html}
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:true}
    disable-swagger-default-url: ${SPRINGDOC_SWAGGER_UI_DISABLE_SWAGGER_DEFAULT_URL:true}
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:true}
    path: ${SPRINGDOC_API_DOCS_PATH:/v3/api-docs}
  show-actuator: ${SPRINGDOC_SHOW_ACTUATOR:true}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:*}
      base-path: ${MANAGEMENT_ENDPOINTS_WEB_BASE_PATH:/actuator}
      cors:
        allowed-origins: ${MANAGEMENT_ENDPOINTS_WEB_CORS_ALLOWED_ORIGINS:*}
  endpoint:
    health:
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:always}
    metrics:
      enabled: ${MANAGEMENT_ENDPOINT_METRICS_ENABLED:true}
    prometheus:
      enabled: ${MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED:true}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.rayfay.gira: ${LOGGING_LEVEL_APP:DEBUG}
    org.springframework.web: ${LOGGING_LEVEL_SPRING_WEB:INFO}
    org.hibernate: ${LOGGING_LEVEL_HIBERNATE:INFO}
  file:
    name: ${LOGGING_FILE_NAME:logs/gira.log}
  pattern:
    console: ${LOGGING_PATTERN_CONSOLE:%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n}
    file: ${LOGGING_PATTERN_FILE:%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n}

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}
    allowed-methods: ${APP_CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS,PATCH}
    allowed-headers: ${APP_CORS_ALLOWED_HEADERS:*}
    allow-credentials: ${APP_CORS_ALLOW_CREDENTIALS:true}
    max-age: ${APP_CORS_MAX_AGE:3600}
  upload:
    location: ${APP_UPLOAD_LOCATION:uploads}
    max-file-size: ${APP_UPLOAD_MAX_FILE_SIZE:10MB}
    allowed-types: ${APP_UPLOAD_ALLOWED_TYPES:image/jpeg,image/png,image/gif,application/pdf}
  websocket:
    endpoint: ${APP_WEBSOCKET_ENDPOINT:/ws}
    allowed-origins: ${APP_WEBSOCKET_ALLOWED_ORIGINS:http://localhost:3000}
    destination-prefix: ${APP_WEBSOCKET_DESTINATION_PREFIX:/topic}
    application-prefix: ${APP_WEBSOCKET_APPLICATION_PREFIX:/app}
  file:
    upload-dir: ${APP_FILE_UPLOAD_DIR:./uploads}
  jwt:
    secret: ${APP_JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration: ${APP_JWT_EXPIRATION:86400000}
    refresh-expiration: ${APP_JWT_REFRESH_EXPIRATION:604800000} 